
title: Personal blog
author: Piotr Wo≈∫nicki
email: piotrekwoznicki@gmail.com
description: This blog focuses on ML applied to radiology.
twitter_username: piotr_woznicki
github_username:  pwoznicki
theme: minima
plugins:
  - jekyll-feed